name:  neevadmin-uat
on:
  push:
    branches:
      - uat

jobs:
  deploy-neevadmin-uat:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright smoke suite
        env:
          REPO: "flyspotorg/playwrightDemoProject"
          EVENT_TYPE: "trigger-playwright-tests"
          CUSTOM_PARAM: "your_value"
          PAT: ${{ secrets.REPO_A_PAT }}
        run: |
          curl -X POST \
          -H "Authorization: token $PAT" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO/dispatches \
          -d '{"event_type":"'"$EVENT_TYPE"'","client_payload":{
            "application": "neevadmin",
            "test_scope": "smoke",
            "test_type": "ALL",
            "env": "uat",
            "run_branch": "main",
            "browser": "chrome",
            "trigger_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }}'