name:  neevadmin-uat
on:
  push:
    branches:
      - uat

jobs:
  deploy-neevadmin-uat:
    uses: flyspotorg/playwrightDemoProject/.github/workflows/playwright-test-run.yml@main
    with:
      application: "neevadmin"
      test_scope: "smoke"
      test_type: "ALL"
      env: "uat"
      run_branch: "main"
      browser: "chrome"
      trigger_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    permissions:
      actions: write