name:  neevadmin-uat
on:
  push:
    branches:
      - uat

jobs:
  deploy-neevadmin-uat:
    runs-on: ubuntu-latest
    steps:

      - name: Dispatch & wait for Playwright regression suite
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{github.owner}}
          repo: playwrightDemoProject
          github_token: ${{ secrets.REPO_A_PAT }}
          workflow_file_name: playwright-test-run.yml
          ref: main
          client_payload: >-
            {
              "application": "neevadmin",
              "test_scope": "smoke",
              "test_type": "ALL",
              "env": "uat",
              "run_branch": "main",
              "trigger_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
          wait_interval: 15
          propagate_failure: true