name: Regression Test Run

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dispatch-and-wait:
    name: Trigger Regression test run and get report
    runs-on: ubuntu-latest

    steps:
      - name: Pause for 30 seconds if another run is in progress
        env:
          GH_TOKEN: ${{ secrets.REPO_A_PAT }}
        run: |
          gh auth status
          CURRENT_RUN_ID=${{ github.run_id }}
          RUNNING_WORKFLOWS=$(gh api repos/${{ github.repository }}/actions/runs --jq '.workflow_runs[] | select(.status=="in_progress" and .name=="${{ github.workflow }}" and .id!='$CURRENT_RUN_ID') | .id')
          if [ -n "$RUNNING_WORKFLOWS" ]; then
            echo "Another run is in progress. Waiting 30 seconds..."
            sleep 30
          else
            echo "No other runs in progress. Proceeding..."
          fi

      - name: Dispatch & wait for regression suite
        id: dispatch_and_wait
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: FlySpotOrg
          repo: playwrightDemoProject
          github_token: ${{ secrets.REPO_A_PAT }}
          workflow_file_name: playwright-test-run.yml
          ref: main
          client_payload: >-
            {"test_scope":"regression"}
          wait_interval: 15
          propagate_failure: true

      - name: Publish report link to action summary
        id: report_summary
        run: |
          RUN_ID=${{ steps.dispatch_and_wait.outputs.workflow_id }}
          CONCLUSION=${{ steps.dispatch_and_wait.outputs.conclusion }}
          if [ "$CONCLUSION" = "success" ]; then
            SYMBOL="✅"
          else
            SYMBOL="❌"
          fi
          echo "### ${SYMBOL} Allure Report: https://flyspotorg.github.io/playwrightDemoProject/regression/${RUN_ID}/" >> $GITHUB_STEP_SUMMARY
          echo "symbol=${SYMBOL}" >> $GITHUB_OUTPUT
          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT

      - name: Publish report link to PR
        if: github.event.pull_request.comments_url
        run: |
          echo "{\"body\":\"### ${{ steps.report_summary.outputs.symbol }} Allure Report: https://flyspotorg.github.io/playwrightDemoProject/regression/${{ steps.report_summary.outputs.run_id }}/\"}" > comment.json
          curl -X POST \
            -H "Authorization: token ${{ secrets.REPO_A_PAT }}" \
            -H "Content-Type: application/json" \
            "${{ github.event.pull_request.comments_url }}" \
            -d @comment.json