name: Regression Test Run

on:
  pull_request:
    types:
        - opened
        - reopened
        - synchronize
  workflow_dispatch:

jobs:
  regression-tests:
    name: Trigger Regression Suite in playwrightDemoProject
    runs-on: ubuntu-latest

    steps:
      - name: Trigger regression test in playwrightDemoProject repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_A_PAT }}  # Personal Access Token (PAT) with repo permissions
          repository: FlySpotOrg/playwrightDemoProject
          event-type: run-regression-tests-from-app-repo
          client-payload: '{"test_scope": "regression", "run_branch": "${{ github.ref_name }}"}'